### PR TITLE
Use 'annotations' instead of 'errors' & 'warnings'

### LINKED ISSUE #19: The library should return just 'annotations' instead of errors and warnings
Dredd doesn't work with errors and warnings separately internally anyway and merges the two lists. It makes no sense to keep it like that in the public interface of this library.

### PR DESCRIPTION
**Pull request by honzajavorek**
Third attempt to close #19, Travis CI to blame this time - see https://github.com/apiaryio/dredd-transactions/pull/113#issuecomment-339314381.

### BREAKING CHANGE

This changes the structure of Dredd Transactions' output. Instead of `errors` and `warnings` arrays, there is now just one array called `annotations`. Individual annotations have `type` property, which can be either `error` or `warning`.

-----

There will be multiple breaking changes. I created `honzajavorek/breaking-changes` branch, which will contain them and once they're all there and reviewed, the branch can be merged into `master`. Thanks to this we should get just one major version bump using the Semantic Release.

This PR is to the `honzajavorek/breaking-changes` branch.

### CODE REVIEW

**Comment by honzajavorek** [comment]
Idea: We could hopefully fix the `commitlint` by using https://github.com/marionebl/commitlint/issues/99#issuecomment-338383135:

```sh
commitlint --from=...the magic from @felixfbecker's comment...
```

File: src/compile.coffee [hunk 1]
```diff
@@ -11,24 +11,22 @@ compile = (mediaType, apiElements, filename) ->
...
 
 
 compileAnnotation = (annotationElement) ->
   {
+    type: annotationElement.classes.getValue(0)
     component: 'apiDescriptionParser'
-    code: annotationElement.code?.toValue()
     message: annotationElement.toValue()
-    location: annotationElement.sourceMapValue
+    location: annotationElement.sourceMapValue or [[0, 1]]
```
Comment (michalholasek) [inline src/compile.coffee]: Why did you add this default value?

File: test/integration/compile-swagger-test.coffee [hunk 2]
```diff
@@ -85,20 +82,26 @@ describe('compile() · Swagger', ->
...
-        assert.deepEqual(compilationResult.transactions[0].request.headers, {
-          'Content-Type': {value: 'application/json'}
-        })
-      )
-      it('with expected response headers', ->
-        assert.deepEqual(compilationResult.transactions[0].response.headers, {})
+    [
+      'application/json'
+      'application/xml'
+      'application/json'
```
Comment (michalholasek) [inline test/integration/compile-swagger-test.coffee]: I think that array items that fit to 80 or 100 column length could be on one line. Just a matter of preference 🙂

File: test/integration/compile-test.coffee [hunk 3]
```diff
@@ -7,7 +7,7 @@ createOriginSchema = require('../schemas/origin')
 {assert, compileFixture} = require('../utils')
 
 
-describe('compile() · all API description formats', ->
+describe.only('compile() · all API description formats', ->
```
Comment (michalholasek) [inline test/integration/compile-test.coffee]: Forgotten `describe.only`?

File: test/integration/compile-test.coffee [hunk 4]
```diff
@@ -91,33 +79,22 @@ describe('compile() · all API description formats', ->
         )
       )
 
-      it('is compiled into zero transactions', ->
-        assert.deepEqual(compilationResult.transactions, [])
+      it('produces some annotations and no transactions', ->
```
Comment (michalholasek) [inline test/integration/compile-test.coffee]: `produces some annotations...` seems a little bit too loose to me, is there any good reason for this? Ditto for other occurrences.

File: src/compile.coffee (hunk 1 above)
Comment (honzajavorek) [reply src/compile.coffee]: Because some annotations seem to be without source map, genuinely. I wanted to keep the behavior consistent, so in case there is no source map, I'm setting "the first character of the first line" as the place of where the problem occurs.

File: test/integration/compile-swagger-test.coffee (hunk 2 above)
Comment (honzajavorek) [reply test/integration/compile-swagger-test.coffee]: Good point. I'd fix it but given the decaf is pending...

File: test/integration/compile-test.coffee (hunk 3 above)
Comment (honzajavorek) [reply test/integration/compile-test.coffee]: 😱 

I really need to stop using it. Since I discovered `npm test -- --grep='all API description formats'` there is no point in using this and it only leads to mistakes like this. And when coverage/coveralls is broken, these mistakes can be very expensive 🙈

File: test/integration/compile-test.coffee (hunk 4 above)
Comment (honzajavorek) [reply test/integration/compile-test.coffee]: It is because of differences in formats. E.g. APIB produces no warning, but Swagger produces one. Every time I've used this, I added further assertions in subsequent `it`s, inspecting the real numbers and types of annotations in the result. At least I hope I did not forget it anywhere.

I was thinking whether this could be done in more declarative way as well, because writing all the `assert.atMost` and `annotations.filter()` etc. is annoying and error-prone. So having sth like

```
{
  annotations:
    {type: 'warning', component: 'apiDescriptionParser', count: 1}
    {type: 'error', countAtMost: 2}
  transactions: 2
}
```

I don't know yet. Just thoughts.

**Comment by honzajavorek** [comment]
I removed the `.only` 🙈 🙂

File: test/integration/compile-test.coffee (hunk 4 above)
Comment (michalholasek) [reply test/integration/compile-test.coffee]: 🤔 I see. I like the solution you proposed (`countAtMost` property, or similar) 👍
